# Generated by Django 4.1.7 on 2023-03-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField()),
                ('application_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_email', models.EmailField(max_length=254)),
                ('borrower_phone', models.CharField(max_length=100)),
                ('borrower_address', models.CharField(max_length=100)),
                ('borrower_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_name', models.CharField(max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('loan_interest', models.IntegerField()),
                ('loan_duration', models.IntegerField()),
                ('loan_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=100)),
                ('user_phone', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=100)),
                ('user_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=100)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_back.applications')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='borrower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_back.borrowers'),
        ),
        migrations.AddField(
            model_name='applications',
            name='loan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_back.loan'),
        ),
    ]
