# Generated by Django 4.1.7 on 2023-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_back', '0002_rename_application_id_applications_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='user_id',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
