# Generated by Django 4.1.7 on 2023-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_back', '0003_alter_loan_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
